hotjs.i18n.put('ru', {
	'language': 'Язык',
	'fastsignup': 'Быстрая регистрация',
	'signup': 'Регистрация',
	'login': 'Вход',
	'logout': 'Выход',
	'available games': 'Доступные игры',
	'login success': 'Успешный вход',
	'not in room': 'Не в комнате',
	'entergame': 'Войти',
	'enter': 'Войти',
	'room number': 'Номер комнаты',
	'gamers in room': 'Игроков в комнате',
	'chat': 'Чат',
	'jinhua1': 'Классическая Цзиньхуа',
	'jinhua2': 'ПК Цзиньхуа',
	'holdem1': 'Холдем (Лимит)',
	'holdem2': 'Холдем (Пот-лимит)',
	'holdem3': 'Холдем (Безлимитный)',
	'exit': 'Выйти',
	'say': 'Сказать',
	'unseat': 'Встать из-за стола',
	'empty': 'пусто',
	'at seat': 'за столом',
	'to bet': 'сделать ставку',
	'delay': 'задержка',
	'seconds': 'секунд',
	'pot': 'Банк',
	'shared cards': 'Общие карты',
	'private cards': 'Карманные карты',
	'my cards': 'Мои карты',
	'bet': 'Ставка',
	'ready': 'Готов',
	'seecard': 'Посмотреть карты',
	'showcard': 'Показать карты',
	'call': 'Колл',
	'raise': 'Рейз',
	'all_in': 'Олл-ин',
	'fold': 'Фолд/Пас',
	'check': 'Чек',
	'pk': 'Сравнение карт',
	'result': 'Результат',
	'win': 'Выигрыш',
	'fail': 'Проигрыш',
	'count down:': 'Обратный отсчет: ',
	'now:': 'Сейчас: ',
	'dealing cards': 'Раздача карт...',
	'game start': 'Игра началась',
	'take seat': 'Сесть за стол',
	'unseat from': 'встал из-за стола',
	'say:': 'говорит: ',
	'shout:': 'кричит: ',
	'game over!': 'Игра окончена!',
	'account created:': 'Аккаунт создан: ',
	'uid': 'UID',
	'passwd': 'Пароль',
	'name': 'Никнейм',
	'email': 'Эл. почта',
	'phone': 'Телефон',
	'uuid': 'UUID',
	'invalid' : 'Недействительно',
	'danzhang': 'Старшая карта',
	'duizi': 'Пара',
	'shunzi': 'Стрит',
	'tonghua': 'Флеш',
	'tonghuashun': 'Стрит-флеш',
	'baozi': 'Сет/Тройка',
	'high card': 'Старшая карта',
	'one pair': 'Одна пара',
	'two pair': 'Две пары',
	'three of a kind': 'Тройка (Сет)',
	'straight': 'Стрит',
	'flush': 'Флеш',
	'fullhouse': 'Фулл-хаус',
	'four of a kind': 'Каре',
	'straight flush': 'Стрит-флеш',
	'royal flush': 'Роял-флеш',
	'invalid rpc req': 'Неверный RPC-запрос',
	'invalid uid or pin, need login first': 'Неверный UID или PIN, сначала необходимо войти в систему',
	'not in room': 'Не в комнате',
	'db err': 'Ошибка базы данных',
	'bad request': 'Некорректный запрос',
	'invalid uid, must be >=3 letters': 'Недопустимый UID, должно быть не менее 3 символов',
	'user exists': 'Пользователь уже существует',
	'user not exists': 'Пользователь не существует',
	'invalid user id or password': 'Неверный идентификатор пользователя или пароль',
	'denied': 'Доступ запрещен',
	'first/D button': 'Кнопка дилера/первого игрока',
});
